OnlineStore/OnlineStore/urls.py
from django.conf import settings  # Импортируем настройки Django
from django.conf.urls.static import (
    static, )  # Импортируем функцию static для обслуживания статических файлов
from django.contrib import admin  # Импортируем модуль администрирования Django
from django.urls import (
    include,
    path,
)  # Импортируем функции include и path для маршрутизации URL

urlpatterns = [
    path("admin/", admin.site.urls),  # URL для панели администратора Django
    path("cart/", include("cart.urls")),  # URL для приложения корзины
    path("about/", include("about.urls")),  # URL для страницы "О нас"
    path("checkout/", include("checkout.urls")),  # URL для оформления заказа
    path("users/", include("users.urls")),  # URL для пользовательских профилей
    path("", include("store.urls")),  # Основной URL для магазина
    path("", include("django.contrib.auth.urls")
         ),  # URL для авторизации и управления пользователями
    path("api/", include("store.api_urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT
                          )  # Добавляем URL для медиафайлов в режиме отладки
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )  # Добавляем URL для статических файлов в режиме отладки

OnlineStore/cart/urls.py
# Импортируем функцию path для создания URL-адресов
from django.urls import path
# Импортируем представления из текущего приложения
from .views import add_to_cart, cart, delete_cart_item, update_cart_item, update_cart_item_form

# Устанавливаем пространство имен для приложения
app_name = 'cart'

# Определяем список URL-адресов
urlpatterns = [
    path('', cart, name='cart'),                                                             # URL для отображения корзины
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),                          # URL для добавления товара в корзину
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),             # URL для удаления товара из корзины
    path('update_cart_item/', update_cart_item, name='update_cart_item'),                    # URL для обновления количества товара в корзине через AJAX
    path('update/<int:cart_item_id>/', update_cart_item_form, name='update_cart_item_form'), # URL для формы обновления количества товара
]

OnlineStore/checkout/urls.py
# Импортируем функцию path для создания URL-адресов
from django.urls import path
# Импортируем представления из текущего приложения
from .views import checkout, create_order, thank_you

# Устанавливаем пространство имен для приложения
app_name = 'checkout'

# Определяем список URL-адресов
urlpatterns = [
    path('', checkout, name='checkout'),                              # Страница оформления заказа
    path('create-order/', create_order, name='create_order'),         # Создание нового заказа
    path('thank-you/<int:order_id>/', thank_you, name='thank_you'),   # Страница благодарности с номером заказа
]

OnlineStore/store/urls.py
from django.urls import path, include  # Импорт функции path из модуля django.urls
from rest_framework.routers import DefaultRouter
from .views import ItemViewSet, ItemTagViewSet, ItemQFilterView
from .views import item_details, store, tag_details, tag_list  # Импорт представлений (views) из текущего приложения
from . import views

app_name = 'store'  # Присвоение имени приложения для идентификации URL в шаблонах и представлениях

# Создание маршрутизатора
# Чтобы API работал, мы должны зарегистрировать эти viewsets в urls.py. Это делается через router:
router = DefaultRouter()
router.register(r'items', ItemViewSet, basename='item')
router.register(r'item-tags', ItemTagViewSet, basename='itemtag')
# router.register(r'items/qfilter', ItemQFilterView, basename='item_qfilter')

urlpatterns = [
    path('', store, name='home'),  # URL для главной страницы магазина, вызывает представление store
    #path('', include(router.urls)),  # Подключение роутера к urls
    path('api/', include(router.urls)),  # Добавление маршрутов API
    path('categories/', tag_list, name='tag_list'),  # URL для страницы со списком категорий, вызывает представление tag_list
    path('category-details/<slug:slug>/', tag_details, name='tag_details'),  # URL для страницы деталей категории по её slug, вызывает представление tag_details
    path('<slug:item_slug>/', item_details, name='item_details'),  # URL для страницы деталей товара по его slug, вызывает представление item_details
    path('api/items/qfilter', ItemQFilterView.as_view(), name='item_qfilter'),
    path('item/<slug:item_slug>/history/', views.item_history, name='item_history'),
]

OnlineStore/cart/models.py
# Импортируем модель пользователя из Django
from django.contrib.auth.models import User

# Импортируем модуль models из Django
from django.db import models

# Импортируем модель Item из приложения store
from store.models import Item


# Определяем модель Cart для представления корзины пользователя
class Cart(models.Model):
    # Поле user связывает корзину с пользователем
    user = models.ForeignKey(
        User,  # Указывает на модель User
        on_delete=models.CASCADE,  # Удаление корзины при удалении пользователя
        related_name="carts",  # Устанавливает имя обратной связи
        verbose_name="Покупатель",  # Имя поля
    )
    # Поле items связано с Item через промежуточную модель CartItem
    items = models.ManyToManyField(  # <--- M2M-поле
        Item,  # Указывает на модель Item
        through="CartItem",  # Указывает промежуточную модель CartItem
        through_fields=("cart", "item"),  # Устанавливает поля для связи
        related_name="carts",  # Устанавливает имя обратной связи
        verbose_name="Товары",  # Имя поля
    )
    # Поле для хранения даты создания корзины
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name="Дата создания")

    # Метаданные модели
    class Meta:
        verbose_name = "Корзина"
        verbose_name_plural = "Корзины"

    # Свойство для расчета общей стоимости корзины
    @property
    def total_price(self):
        return sum(cart_item.total_price
                   for cart_item in self.cart_items.all())

    # Метод для пересчета общей стоимости корзины
    # def recalculate_total_price(self):
    #     self.total_price = sum(cart_item.total_price for cart_item in self.cart_items.all())
    #     self.save()

    # Метод для строкового представления корзины
    def __str__(self):
        return f"Cart {self.id} for {self.user.username}"

    # Метод для очистки корзины
    def clear(self):
        self.cart_items.all().delete(
        )  # Удаляет все записи CartItem для данной корзины
        self.items.clear()


# Определяем модель CartItem для представления товара в корзине
class CartItem(models.Model):
    # Поле cart связывает товар с корзиной
    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE,
        related_name="cart_items",
        verbose_name="Корзина",
    )
    # Поле item связывает товар с моделью Item
    item = models.ForeignKey(Item,
                             on_delete=models.CASCADE,
                             verbose_name="Товар")
    # Поле quantity хранит количество данного товара в корзине
    quantity = models.PositiveIntegerField(default=1,
                                           verbose_name="Количество")

    # Метаданные модели
    class Meta:
        verbose_name = "Товар в корзине"
        verbose_name_plural = "Товары в корзине"

    # Свойство для расчета стоимости данной позиции в корзине
    @property
    def total_price(self):
        return self.quantity * self.item.price

    # Метод для строкового представления товара в корзине
    def __str__(self):
        return f"{self.quantity} x {self.item.title}"

OnlineStore/cart/forms.py
# Импортируем модуль forms из Django
from django import forms

# Импортируем модель CartItem из текущего приложения
from .models import CartItem


# Определяем форму для добавления товара в корзину
class AddToCartForm(forms.Form):
    # Поле для идентификатора товара, скрытое в форме
    item_id = forms.IntegerField(widget=forms.HiddenInput())


# Определяем форму для обновления количества товара в корзине
class UpdateCartItemForm(forms.ModelForm):
    # Мета-класс для указания модели и полей, которые будут использованы в
    # форме
    class Meta:
        model = CartItem
        fields = ["quantity"]
        # Настройка виджета для поля quantity, чтобы применить CSS-класс
        # 'quantity-input'
        widgets = {
            "quantity": forms.NumberInput(attrs={"class": "quantity-input"}),
        }

    # Метод для валидации поля quantity
    def clean_quantity(self):
        # Получаем очищенное значение quantity из формы
        quantity = self.cleaned_data["quantity"]
        # Если количество меньше 1, выбрасываем исключение ValidationError
        if quantity < 1:
            raise forms.ValidationError("Quantity must be at least 1.")
        return quantity

    # Переопределение метода clean для дополнительной обработки данных
    def clean(self):
        # Вызываем оригинальный метод clean у родительского класса
        cleaned_data = super().clean()
        # Получаем очищенное значение quantity
        quantity = cleaned_data.get("quantity")
        return cleaned_data

OnlineStore/cart/views.py
# Импортируем необходимые модули и функции из Django
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from store.models import Item  # Импортируем модель товара из приложения store
from .models import Cart, CartItem  # Импортируем модели корзины и элемента корзины из текущего приложения
from .forms import UpdateCartItemForm  # Импортируем форму для обновления элемента корзины


# Представление для вывода всех объектов товаров корзины и самой корзины
@login_required  # Декоратор для требования аутентификации пользователя
def cart(request):
    # Получаем корзину текущего пользователя
    cart = Cart.objects.filter(user=request.user).first()

    # Если у пользователя нет корзины, создаем новую
    if not cart:
        cart = Cart.objects.create(user=request.user)

    # Формируем контекст для передачи в шаблон
    context = {
        'cart_items': CartItem.objects.filter(cart=cart),  # Получаем все элементы корзины для текущей корзины
        'cart': cart  # Передаем объект корзины в контекст
    }

    # Отображаем шаблон cart.html с переданным контекстом
    return render(request, 'cart/cart.html', context)


 # Представление для добавления товара в корзину, либо увеличения его количества на 1
@login_required  # Декоратор для требования аутентификации пользователя
def add_to_cart(request, item_slug):
    # Получаем товар по его slug
    item = get_object_or_404(Item, slug=item_slug)

    # Получаем корзину пользователя или создаем новую, если её нет
    cart, _ = Cart.objects.get_or_create(user=request.user)

    # Получаем или создаем элемент корзины для данного товара
    cart_item, created = CartItem.objects.get_or_create(
        cart=cart,
        item=item
    )

    # Если элемент корзины не был создан заново, увеличиваем его количество на 1
    if not created:
        cart_item.quantity += 1
        cart_item.save()

    # Перенаправляем пользователя на страницу корзины
    return redirect('cart:cart')


 # Представление для удаления объекта товара в корзине
@login_required  # Декоратор для требования аутентификации пользователя
def delete_cart_item(request, item_slug):
    # Находим элемент корзины по товару и пользователю
    cart_item = CartItem.objects.get(
        cart=Cart.objects.get(user=request.user),
        item=get_object_or_404(Item, slug=item_slug)
    )

    # Удаляем элемент корзины
    cart_item.delete()

    # Перенаправляем пользователя на страницу корзины
    return redirect('cart:cart')


# Представление для обработки AJAX-запроса и последующего обновления БД
# и отправки на страницу JSON-ответа с необходимыми данными
@require_POST  # Декоратор для требования POST-запроса
@login_required  # Декоратор для требования аутентификации пользователя
def update_cart_item(request):
    # Получаем данные из формы обновления элемента корзины
    form = UpdateCartItemForm(request.POST)

    # Проверяем валидность данных формы
    if form.is_valid():
        cart_item_id = form.cleaned_data['cart_item_id']  # Получаем ID элемента корзины из формы
        new_quantity = form.cleaned_data['quantity']  # Получаем новое количество товара из формы

        # Находим элемент корзины по его ID и пользователю
        cart_item = get_object_or_404(CartItem, id=cart_item_id, cart__user=request.user)

        # Обновляем количество товара в элементе корзины
        cart_item.quantity = new_quantity
        cart_item.save()

        # Пересчитываем общую стоимость корзины
        cart_item.cart.recalculate_total_price()

        # Возвращаем JSON-ответ с успешными данными обновления
        return JsonResponse({
            'success': True,
            'cart_item_id': cart_item.id,
            'cart_item_quantity': cart_item.quantity,
            'cart_item_total_price': cart_item.total_price,
            'cart_total_price': cart_item.cart.total_price
        })
    else:
        # Возвращаем JSON-ответ с сообщением об ошибке в данных формы
        return JsonResponse({
            'success': False,
            'error': 'Invalid data submitted'
        })


# Представление для обновления количества товара в корзине
@login_required  # Декоратор для требования аутентификации пользователя
def update_cart_item_form(request, cart_item_id):
    # Находим элемент корзины по его ID и пользователю
    cart_item = get_object_or_404(CartItem, id=cart_item_id, cart__user=request.user)

    # Если запрос пришел методом POST, обрабатываем данные формы обновления
    if request.method == 'POST':
        form = UpdateCartItemForm(request.POST, instance=cart_item)
        if form.is_valid():
            form.save()  # Сохраняем данные формы
            return redirect('cart:cart')  # Перенаправляем пользователя на страницу корзины
    else:
        form = UpdateCartItemForm(instance=cart_item)  # Создаем форму для обновления данных элемента корзины

    # Формируем контекст для передачи в шаблон обновления элемента корзины
    context = {
        'form': form,
        'cart_item': cart_item
    }

    # Отображаем шаблон update_cart_item.html с переданным контекстом
    return render(request, 'cart/update_cart_item.html', context)

OnlineStore/templates/cart/cart.html
{% extends 'base.html' %} <!-- Наследуемся от базового шаблона base.html -->

{% load static %} <!-- Загружаем тег static для использования статических файлов -->
{% block css %} <!-- Начало блока css, который будет вставлен в блок css базового шаблона -->
  <link rel="stylesheet" href="{% static "assets/css/cart.css" %}" /> <!-- Подключаем файл стилей для корзины -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <!-- Подключаем библиотеку jQuery -->
{% endblock %}

{% block content %} <!-- Начало блока content, который будет вставлен в блок content базового шаблона -->
<h1>Корзина</h1> <!-- Заголовок страницы -->
{% if cart_items %} <!-- Проверяем, есть ли товары в корзине -->
  <section> <!-- Начало секции корзины -->
    <div class="table-wrapper"> <!-- Обертка для таблицы -->
      <table class="alt"> <!-- Таблица для отображения товаров в корзине -->
        <thead>
          <tr>
            <th>Название</th>
            <th>Количество</th>
            <th>Цена</th>
          </tr>
        </thead>
        <tbody>
          {% for cart_item in cart_items %} <!-- Перебор всех товаров в корзине -->
          <tr>
            <td><a href="{% url 'store:item_details' cart_item.item.slug %}">{{ cart_item.item.title }}</a></td> <!-- Ссылка на детальную страницу товара -->
            <td>
                <div class="count"> <!-- Обертка для управления количеством товара -->
                    <span class="minus" data-cart-item-id="{{ cart_item.id }}">—</span> <!-- Кнопка уменьшения количества -->
                    <input type="number" value="{{ cart_item.quantity }}" class="quantity-input" data-cart-item-id="{{ cart_item.id }}"> <!-- Поле ввода количества -->
                    <span class="plus" data-cart-item-id="{{ cart_item.id }}">+</span> <!-- Кнопка увеличения количества -->
                </div>
                <form id="update-cart-item-form-{{ cart_item.id }}" method="POST" action="{% url 'cart:update_cart_item' %}" style="display:none;"> <!-- Форма для обновления количества товара в корзине -->
                    {% csrf_token %} <!-- CSRF токен для защиты формы -->
                    <input type="hidden" id="new-quantity-input-{{ cart_item.id }}" name="new_quantity"> <!-- Скрытое поле для нового количества -->
                    <input type="hidden" id="cart-item-id-input-{{ cart_item.id }}" name="cart_item_id"> <!-- Скрытое поле для ID товара в корзине -->
                </form>
            </td>
            <td class="cart-item-total-price" data-cart-item-id="{{ cart_item.id }}">{{ cart_item.total_price }}</td> <!-- Отображение общей стоимости товара -->
            <td style="border: none; background-color: #ffffff;" align="center"> <!-- Ячейка для кнопки удаления товара -->
                <a href="{% url 'cart:delete_cart_item' cart_item.item.slug %}"> <!-- Ссылка для удаления товара из корзины -->
                    <img src="{% static "images/garbage.svg" %}" width="25" height="25"> <!-- Иконка корзины для удаления -->
                </a>
            </td>
          </tr>
          {% endfor %} <!-- Конец перебора товаров в корзине -->
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"></td>
            <td><u><b><span id="cart-total-price" data-cart-id="{{ cart.id }}">{{ cart.total_price }}</span></b></u></td> <!-- Отображение общей стоимости всех товаров в корзине -->
          </tr>
        </tfoot>
      </table>
    </div>
  </section>
  <div style="text-align: justify;">
    <a href="{% url 'store:home' %}" style="float: left;" class="button">Продолжить покупки</a> <!-- Ссылка для продолжения покупок -->
    <a href="{% url 'checkout:checkout' %}" style="float: right;" class="button">Оформить заказ</a> <!-- Ссылка для оформления заказа -->
  </div>
{% else %} <!-- Если корзина пуста -->
  <p>Ваша корзина пуста.</p> <!-- Сообщение о пустой корзине -->
{% endif %}
{% block js %} <!-- Начало блока js, который будет вставлен в блок js базового шаблона -->
  <script src="{% static "assets/js/ajax.js" %}"></script> <!-- Подключение пользовательского скрипта ajax.js -->
  <script>
    $(document).ready(function() { <!-- Убедиться, что DOM полностью загружен -->
      // Обработка изменения количества товаров
      $('.quantity-input').on('change', function() { <!-- Событие изменения количества товаров -->
        var newQuantity = $(this).val(); <!-- Получаем новое количество -->
        var cartItemId = $(this).data('cart-item-id'); <!-- Получаем ID товара в корзине -->
        $('.new-quantity-input').val(newQuantity); <!-- Обновляем значение скрытого поля -->
        $('.update-cart-item-form[data-cart-item-id="' + cartItemId + '"]').submit(); <!-- Отправляем форму обновления товара -->
      });
    });
  </script>
{% endblock %}
{% endblock %}

OnlineStore/templates/cart/update_cart_item.html
{% extends 'base.html' %} <!-- Наследуемся от базового шаблона base.html -->

{% load static %} <!-- Загружаем тег static для использования статических файлов -->

{% block css %} <!-- Начало блока css, который будет вставлен в блок css базового шаблона -->
<link rel="stylesheet" href="{% static "assets/css/cart.css" %}" /> <!-- Подключаем файл стилей для корзины -->
{% endblock %}

{% block content %} <!-- Начало блока content, который будет вставлен в блок content базового шаблона -->
<h1>Обновить количество товара</h1> <!-- Заголовок страницы -->

<!-- Форма для обновления количества товара -->
<form method="post" action="{% url 'cart:update_cart_item_form' cart_item.id %}">
  {% csrf_token %} <!-- CSRF токен для защиты формы -->
  {{ form.as_p }} <!-- Рендеринг формы с полями в виде параграфов -->
  <button type="submit" class="button">Обновить</button> <!-- Кнопка отправки формы -->
</form>

<!-- Ссылка для возврата в корзину -->
<a href="{% url 'cart:cart' %}" class="button">Вернуться в корзину</a>
{% endblock %}