OnlineStore/OnlineStore/urls.py
from django.conf import settings  # Импортируем настройки Django
from django.conf.urls.static import (
    static, )  # Импортируем функцию static для обслуживания статических файлов
from django.contrib import admin  # Импортируем модуль администрирования Django
from django.urls import (
    include,
    path,
)  # Импортируем функции include и path для маршрутизации URL

urlpatterns = [
    path("admin/", admin.site.urls),  # URL для панели администратора Django
    path("cart/", include("cart.urls")),  # URL для приложения корзины
    path("about/", include("about.urls")),  # URL для страницы "О нас"
    path("checkout/", include("checkout.urls")),  # URL для оформления заказа
    path("users/", include("users.urls")),  # URL для пользовательских профилей
    path("", include("store.urls")),  # Основной URL для магазина
    path("", include("django.contrib.auth.urls")
         ),  # URL для авторизации и управления пользователями
    path("api/", include("store.api_urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT
                          )  # Добавляем URL для медиафайлов в режиме отладки
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )  # Добавляем URL для статических файлов в режиме отладки

OnlineStore/about/urls.py
# Импортируем функцию path для определения маршрутов URL
from django.urls import path

# Импортируем представления из текущего пакета (папки)
from .views import AboutAuthorView, AboutProjectView

# Задаем пространство имен для URL, чтобы можно было ссылаться на них
# через app_name
app_name = "about"

# Определяем список маршрутов URL для приложения
urlpatterns = [
    # URL для страницы проекта. Связываем маршрут 'project/' с представлением AboutProjectView.
    # as_view() используется для создания экземпляра класса представления.
    path("project/", AboutProjectView.as_view(), name="about_project"),
    # URL для страницы автора. Связываем маршрут 'me/' с представлением
    # AboutAuthorView.
    path("me/", AboutAuthorView.as_view(), name="about_me"),
]

OnlineStore/cart/urls.py
# Импортируем функцию path для создания URL-адресов
from django.urls import path
# Импортируем представления из текущего приложения
from .views import add_to_cart, cart, delete_cart_item, update_cart_item, update_cart_item_form

# Устанавливаем пространство имен для приложения
app_name = 'cart'

# Определяем список URL-адресов
urlpatterns = [
    path('', cart, name='cart'),                                                             # URL для отображения корзины
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),                          # URL для добавления товара в корзину
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),             # URL для удаления товара из корзины
    path('update_cart_item/', update_cart_item, name='update_cart_item'),                    # URL для обновления количества товара в корзине через AJAX
    path('update/<int:cart_item_id>/', update_cart_item_form, name='update_cart_item_form'), # URL для формы обновления количества товара
]

OnlineStore/store/urls.py
from django.urls import path, include  # Импорт функции path из модуля django.urls
from rest_framework.routers import DefaultRouter
from .views import ItemViewSet, ItemTagViewSet, ItemQFilterView
from .views import item_details, store, tag_details, tag_list  # Импорт представлений (views) из текущего приложения
from . import views

app_name = 'store'  # Присвоение имени приложения для идентификации URL в шаблонах и представлениях

# Создание маршрутизатора
# Чтобы API работал, мы должны зарегистрировать эти viewsets в urls.py. Это делается через router:
router = DefaultRouter()
router.register(r'items', ItemViewSet, basename='item')
router.register(r'item-tags', ItemTagViewSet, basename='itemtag')
# router.register(r'items/qfilter', ItemQFilterView, basename='item_qfilter')

urlpatterns = [
    path('', store, name='home'),  # URL для главной страницы магазина, вызывает представление store
    #path('', include(router.urls)),  # Подключение роутера к urls
    path('api/', include(router.urls)),  # Добавление маршрутов API
    path('categories/', tag_list, name='tag_list'),  # URL для страницы со списком категорий, вызывает представление tag_list
    path('category-details/<slug:slug>/', tag_details, name='tag_details'),  # URL для страницы деталей категории по её slug, вызывает представление tag_details
    path('<slug:item_slug>/', item_details, name='item_details'),  # URL для страницы деталей товара по его slug, вызывает представление item_details
    path('api/items/qfilter', ItemQFilterView.as_view(), name='item_qfilter'),
    path('item/<slug:item_slug>/history/', views.item_history, name='item_history'),
]

OnlineStore/users/urls.py
# Импортируем необходимые представления из django.contrib.auth.views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)

# Импортируем path и reverse_lazy из django.urls для работы с URL и
# отложенными URL-обратками
from django.urls import path, reverse_lazy

# Импортируем пользовательские представления из текущего приложения
from .views import SignUp, feedback_processing, profile, user_orders

# Указываем пространство имен для приложения, чтобы отличать URL разных
# приложений
app_name = "users"

# Определяем список URL-шаблонов для текущего приложения
urlpatterns = [
    # URL для просмотра заказов пользователя, связанный с представлением
    # user_orders
    path("orders/", user_orders, name="user_orders"),
    # URL для просмотра профиля пользователя, связанный с представлением
    # profile
    path("profile/", profile, name="profile"),
    # URL для обработки обратной связи, связанный с представлением
    # feedback_processing
    path("feedback-processing/",
         feedback_processing,
         name="feedback_processing"),
    # URL для выхода из системы, использующий стандартное представление
    # LogoutView
    path(
        "auth/logout/",
        LogoutView.as_view(template_name="users/logged_out.html"
                           ),  # Указываем шаблон для отображения после выхода
        name="logout",
    ),
    # URL для регистрации нового пользователя, связанный с представлением
    # SignUp
    path("auth/signup/", SignUp.as_view(), name="signup"),
    # URL для входа в систему, использующий стандартное представление LoginView
    path(
        "auth/login/",
        LoginView.as_view(template_name="users/login.html"
                          ),  # Указываем шаблон для отображения формы входа
        name="login",
    ),
    # URL для сброса пароля, использующий стандартное представление
    # PasswordResetView
    path(
        "auth/password_reset/",
        PasswordResetView.as_view(
            # Шаблон для формы сброса пароля
            template_name="users/managment/password_reset_form.html",
            # Шаблон для email сброса пароля
            email_template_name="users/managment/password_reset_email.html",
            success_url=reverse_lazy(
                "users:password_reset_done"
            ),  # URL для перенаправления после успешного сброса
        ),
        name="password_reset_form",
    ),
    # URL для подтверждения сброса пароля, использующий стандартное
    # представление PasswordResetDoneView
    path(
        "auth/password_reset/done/",
        PasswordResetDoneView.as_view(
            # Шаблон для отображения после отправки email
            template_name="users/managment/password_reset_done.html"),
        name="password_reset_done",
    ),
    # URL для завершения сброса пароля, использующий стандартное представление
    # PasswordResetCompleteView
    path(
        "auth/reset/done/",
        PasswordResetCompleteView.as_view(
            # Шаблон для отображения после успешного сброса
            template_name="users/managment/reset_done.html"),
        name="reset_done",
    ),
    # URL для подтверждения сброса пароля, использующий стандартное
    # представление PasswordResetConfirmView
    path(
        "auth/password_reset_confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            # Шаблон для формы подтверждения сброса
            template_name="users/managment/password_reset_confirm.html",
            success_url=reverse_lazy(
                "users:password_reset_complete"
            ),  # URL для перенаправления после подтверждения
        ),
        name="password_reset_confirm",
    ),
    # URL для изменения пароля, использующий стандартное представление
    # PasswordChangeView
    path(
        "auth/password_change/",
        PasswordChangeView.as_view(
            # Шаблон для формы изменения пароля
            template_name="users/managment/password_change_form.html",
            success_url=reverse_lazy(
                "users:password_change_done"
            ),  # URL для перенаправления после изменения
        ),
        name="password_change",
    ),
    # URL для подтверждения изменения пароля, использующий стандартное
    # представление PasswordChangeDoneView
    path(
        "auth/password_change/done/",
        PasswordChangeDoneView.as_view(
            # Шаблон для отображения после изменения
            template_name="users/managment/password_change_done.html"),
        name="password_change_done",
    ),
]

OnlineStore/templates/includes/footer.html
<footer id="footer"> <!-- Начало футера с уникальным идентификатором footer -->
    <div class="inner"> <!-- Внутренняя область футера -->
        <section> <!-- Первая секция в футере -->
            <h2>Остались вопросы? Свяжитесь с нами</h2> <!-- Заголовок первой секции -->
            <form method="post" action="{% url 'users:feedback_processing'%}"> <!-- Форма для отправки обратной связи, метод POST -->
                {% csrf_token %} <!-- CSRF-токен для защиты от межсайтовой подделки запросов -->
                <div class="fields"> <!-- Контейнер для полей формы -->
                    <div class="field half"> <!-- Первое поле формы, половина ширины -->
                        <input type="text" name="feedback_name" id="feedback_name" placeholder="Имя" /> <!-- Поле для ввода имени -->
                    </div>
                    <div class="field half"> <!-- Второе поле формы, половина ширины -->
                        <input type="email" name="feedback_email" id="feedback_email" placeholder="Почта" /> <!-- Поле для ввода email -->
                    </div>
                    <div class="field"> <!-- Третье поле формы, полная ширина -->
                        <textarea name="feedback_message" id="feedback_message" placeholder="Сообщение"></textarea> <!-- Поле для ввода сообщения -->
                    </div>
                </div>
                <ul class="actions"> <!-- Контейнер для действий -->
                    <li><input type="submit" value="Отправить" class="primary" /></li> <!-- Кнопка отправки формы -->
                </ul>
            </form>
        </section>
        <section> <!-- Вторая секция в футере -->
            <h2>Мои ресурсы</h2> <!-- Заголовок второй секции -->
            <ul class="icons"> <!-- Список иконок -->
                <li><a href="https://github.com/Bakhadyr04" class="icon brands style2 fa-github"><span class="label">GitHub</span></a></li> <!-- Ссылка на GitHub -->
                <li><a href="https://t.me/FIT231_322" class="icon solid style2 fa-phone"><span class="label">Telegram</span></a></li> <!-- Ссылка на Telegram -->
                <li><a href="mailto:bahadyr2004@mail.ru" class="icon solid style2 fa-envelope"><span class="label">Email</span></a></li> <!-- Ссылка на Email -->
            </ul>
        </section>
    </div>
</footer> <!-- Завершение футера -->

OnlineStore/templates/includes/header.html
{% load static %} <!-- Загрузка тега static для работы с статическими файлами -->

<header id="header"> <!-- Начало верхнего меню с уникальным идентификатором header -->
    <div class="inner"> <!-- Внутренняя область верхнего меню -->
        <!-- Logo -->
        <a href="{% url 'store:home' %}" class="logo"> <!-- Ссылка на главную страницу с классом logo -->
            <span class="symbol"><img src="{% static "images/logo.svg" %}" alt="" /></span> <!-- Иконка логотипа -->
            <span class="title">Hype Shop</span> <!-- Текстовое название логотипа -->
        </a>
        <!-- Nav -->
        <nav> <!-- Навигационное меню -->
            <ul> <!-- Список элементов меню -->
                <li><a href="#menu">Menu</a></li> <!-- Элемент меню "Menu" -->
            </ul>
            <br> <!-- Разрыв строки -->
            <ul class="actions"> <!-- Контейнер для действий, например, ссылок на корзину и профиль -->
                <li>
                    <a href="{% url 'cart:cart' %}"> <!-- Ссылка на страницу корзины -->
                        <img src="{% static "images/cart.jpg" %}" width="40" height="40" > <!-- Иконка корзины -->
                    </a>
                    <br> <!-- Разрыв строки -->
                    <a href="{% url 'users:profile' %}"> <!-- Ссылка на профиль пользователя -->
                        <img src="{% static "images/profile.png" %}" width="40" height="40" > <!-- Иконка профиля -->
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</header>
<!-- Menu -->
<nav id="menu"> <!-- Меню с уникальным идентификатором menu -->
    <h2>Меню</h2> <!-- Заголовок меню -->
    <ul> <!-- Список элементов меню -->
        <li><a href="{% url 'store:tag_list' %}">Все категории</a></li> <!-- Элемент меню для всех категорий -->
        <li><a href="{% url 'about:about_project' %}">О проекте</a></li> <!-- Элемент меню для страницы "О проекте" -->
        <li><a href="{% url 'about:about_me' %}">Обо мне</a></li> <!-- Элемент меню для страницы "Обо мне" -->
    </ul>
</nav>

OnlineStore/templates/includes/paginator.html
<!--каждая часть шаблона обрабатывает и отображает элементы пагинации,-->
<!--включая предыдущую и следующую страницы, текущую страницу и доступные страницы для перехода.-->

{% if page_obj.has_previous %}
  <!-- Предыдущая страница -->
  <a href="?page={{ page_obj.previous_page_number }}" class="button small">Prev</a>
{% else %}
  <!-- Если нет предыдущей страницы, ссылка отключена -->
  <a class="button small disabled">Prev</a>
{% endif %}

{% for i in page_obj.paginator.page_range %}
  {% if page_obj.number == i %}
    <!-- Текущая страница -->
    <a href="#" class="button small disabled">{{ i }}</a>
  {% else %}
    <!-- Ссылки на другие страницы -->
    <a href="?page={{ i }}" class="button small">{{ i }}</a>
  {% endif %}
{% endfor %}

{% if page_obj.has_next %}
  <!-- Следующая страница -->
  <a href="?page={{ page_obj.next_page_number }}" class="button small">Next</a>
{% else %}
  <!-- Если нет следующей страницы, ссылка отключена -->
  <a class="button small disabled">Next</a>
{% endif %}