OnlineStore/OnlineStore/urls.py
from django.conf import settings  # Импортируем настройки Django
from django.conf.urls.static import (
    static, )  # Импортируем функцию static для обслуживания статических файлов
from django.contrib import admin  # Импортируем модуль администрирования Django
from django.urls import (
    include,
    path,
)  # Импортируем функции include и path для маршрутизации URL

urlpatterns = [
    path("admin/", admin.site.urls),  # URL для панели администратора Django
    path("cart/", include("cart.urls")),  # URL для приложения корзины
    path("about/", include("about.urls")),  # URL для страницы "О нас"
    path("checkout/", include("checkout.urls")),  # URL для оформления заказа
    path("users/", include("users.urls")),  # URL для пользовательских профилей
    path("", include("store.urls")),  # Основной URL для магазина
    path("", include("django.contrib.auth.urls")
         ),  # URL для авторизации и управления пользователями
    path("api/", include("store.api_urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT
                          )  # Добавляем URL для медиафайлов в режиме отладки
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )  # Добавляем URL для статических файлов в режиме отладки

OnlineStore/cart/urls.py
# Импортируем функцию path для создания URL-адресов
from django.urls import path
# Импортируем представления из текущего приложения
from .views import add_to_cart, cart, delete_cart_item, update_cart_item, update_cart_item_form

# Устанавливаем пространство имен для приложения
app_name = 'cart'

# Определяем список URL-адресов
urlpatterns = [
    path('', cart, name='cart'),                                                             # URL для отображения корзины
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),                          # URL для добавления товара в корзину
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),             # URL для удаления товара из корзины
    path('update_cart_item/', update_cart_item, name='update_cart_item'),                    # URL для обновления количества товара в корзине через AJAX
    path('update/<int:cart_item_id>/', update_cart_item_form, name='update_cart_item_form'), # URL для формы обновления количества товара
]

OnlineStore/store/urls.py
from django.urls import path, include  # Импорт функции path из модуля django.urls
from rest_framework.routers import DefaultRouter
from .views import ItemViewSet, ItemTagViewSet, ItemQFilterView
from .views import item_details, store, tag_details, tag_list  # Импорт представлений (views) из текущего приложения
from . import views

app_name = 'store'  # Присвоение имени приложения для идентификации URL в шаблонах и представлениях

# Создание маршрутизатора
# Чтобы API работал, мы должны зарегистрировать эти viewsets в urls.py. Это делается через router:
router = DefaultRouter()
router.register(r'items', ItemViewSet, basename='item')
router.register(r'item-tags', ItemTagViewSet, basename='itemtag')
# router.register(r'items/qfilter', ItemQFilterView, basename='item_qfilter')

urlpatterns = [
    path('', store, name='home'),  # URL для главной страницы магазина, вызывает представление store
    #path('', include(router.urls)),  # Подключение роутера к urls
    path('api/', include(router.urls)),  # Добавление маршрутов API
    path('categories/', tag_list, name='tag_list'),  # URL для страницы со списком категорий, вызывает представление tag_list
    path('category-details/<slug:slug>/', tag_details, name='tag_details'),  # URL для страницы деталей категории по её slug, вызывает представление tag_details
    path('<slug:item_slug>/', item_details, name='item_details'),  # URL для страницы деталей товара по его slug, вызывает представление item_details
    path('api/items/qfilter', ItemQFilterView.as_view(), name='item_qfilter'),
    path('item/<slug:item_slug>/history/', views.item_history, name='item_history'),
]

OnlineStore/store/models.py
# Импортируем модуль для работы с моделями Django
from django.db import models
from django.utils.text import slugify
# Импортируем функцию для локализации строковых данных
from django.utils.translation import gettext_lazy as _
# Импортируем менеджер для работы с тегами
from taggit.managers import TaggableManager
# Импортируем базовые классы для тегов
from taggit.models import GenericTaggedItemBase, TagBase

from django.contrib.auth.models import User
from django.utils import timezone

from simple_history.models import HistoricalRecords

from django.core.exceptions import ValidationError
import re


# Определяем модель тега товара
class ItemTag(TagBase):
    # Поле для изображения категории
    image = models.ImageField(
        upload_to='categories/',  # Путь для сохранения изображения
        verbose_name='Изображение',  # Имя поля
        blank=True  # Поле необязательно для заполнения
    )
    # Поле для описания категории
    description = models.TextField(
        blank=True,  # Поле необязательно для заполнения
        verbose_name='Описание',  # Имя поля
    )

    class Meta:
        verbose_name = _("Категория")  # Отображаемое имя в единственном числе
        verbose_name_plural = _("Категории")  # Отображаемое имя во множественном числе

# Определяем модель связи тега с товаром
class TaggedItem(GenericTaggedItemBase):
    # Внешний ключ на модель ItemTag с удалением зависимостей
    tag = models.ForeignKey(
        ItemTag,
        on_delete=models.CASCADE,
        related_name="items",  # Обратная связь для доступа к тегам через модель ItemTag
        verbose_name='Категория',  # Имя поля
    )

# Определяем модель товара
class Item(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')  # Название товара
    description = models.TextField(verbose_name='Описание')  # Описание товара
    slug = models.CharField(
        unique=True,  # Уникальное значение
        max_length=50,  # Максимальная длина
    )
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')  # Дата добавления товара
    price = models.DecimalField(
        max_digits=8,  # Максимальное количество цифр в числе
        decimal_places=2,  # Количество знаков после запятой
        verbose_name='Новая цена',  # Имя поля
    )
    old_price = models.DecimalField(
        max_digits=8,  # Максимальное количество цифр в числе
        decimal_places=2,  # Количество знаков после запятой
        verbose_name='Старая цена',  # Имя поля
        blank=True,  # Поле необязательно для заполнения
        null=True,  # Поле может содержать значение null
    )
    image = models.ImageField(
        verbose_name='Изображение',  # Имя поля
        upload_to='items/',  # Путь для сохранения изображения
        blank=True,  # Поле необязательно для заполнения
        default='path/to/default/image.jpg'
    )
    is_available = models.BooleanField(
        default=True,  # Значение по умолчанию
        verbose_name='Доступно',  # "Говорящее" имя поля
    )
    tags = TaggableManager(through=TaggedItem, related_name="tagged_items", verbose_name='Категории')  # Менеджер для работы с тегами
    history = HistoricalRecords()  # Добавляем историю изменений модели

    def clean(self):
        errors = {}

        # Проверка цены
        if self.price is not None and self.price <= 0:
            errors['price'] = 'Цена должна быть больше нуля.'

        # Проверка длины title
        if len(self.title) <= 3:
            errors['title'] = 'Название должно быть не менее 3 символов.'

        # Проверка длины description
        if len(self.description) <= 3:
            errors['description'] = 'Описание должно быть не менее 3 символов.'

        # Проверка символов в title
        if not re.match(r'^[a-zA-Zа-яА-Я0-9\s]+$', self.title):
            errors['title'] = 'Название должно содержать только буквы и цифры.'

        # Проверка символов в description
        if not re.match(r'^[a-zA-Zа-яА-Я0-9\s]+$', self.description):
            errors['description'] = 'Описание должно содержать только буквы и цифры.'

        # Если есть ошибки, выбрасываем исключение
        if errors:
            raise ValidationError(errors)


    def save(self, *args, **kwargs):
        self.full_clean()  # Вызываем валидацию перед сохранением объекта

        if not self.slug:
            self.slug = slugify(self.title)  # Генерация slug из названия товара

        super().save(*args, **kwargs)  # Вызов метода save родительского класса



    def __str__(self):
        return self.title  # Возвращает название товара при приведении к строке

    class Meta:
        ordering = ['-price']  # Сортировка товаров по убыванию цены
        verbose_name = 'Товар'  # Имя модели в единственном числе
        verbose_name_plural = 'Товары'  # Имя модели во множественном числе




#Создаем модель ChangeHistory для хранения информации об изменениях объектов

class ChangeHistory(models.Model):
    object_type = models.CharField(max_length=255)
    object_id = models.PositiveIntegerField()
    changed_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    change_type = models.CharField(max_length=50, choices=[('add', 'Add'), ('update', 'Update'), ('delete', 'Delete')])
    old_value = models.JSONField(null=True, blank=True)
    new_value = models.JSONField(null=True, blank=True)
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.object_type} {self.change_type} at {self.timestamp}"

OnlineStore/store/views.py
from django.db.models import Q, F
from django.shortcuts import get_object_or_404, render  # Импорт функций get_object_or_404 и render из django.shortcuts
from django_filters.rest_framework import DjangoFilterBackend

from rest_framework import viewsets, status, serializers
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.decorators import action

from .filters import ItemFilter
from .models import Item, ItemTag, ChangeHistory  # Импорт моделей Item и ItemTag из текущего приложения
from .paginator import paginator  # Импорт функции paginator из файла paginator.py

from .serializers import ItemTagSerializer, ItemSerializer


def store(request):
    """
    Представление для главной страницы магазина. Отображает список доступных товаров с пагинацией
    """
    items = Item.objects.filter(is_available=True)  # Получение списка доступных товаров
    context = {
        'page_obj': paginator(request, items, 9),  # Пагинация списка товаров по 9 на странице
        'range': [*range(1, 7)],  # Для случайных CSS стилей, создание списка чисел от 1 до 6
    }
    return render(request, 'store/main_page.html', context)  # Отображение главной страницы с контекстом


def item_details(request, item_slug):
    """
    Представление для страницы с деталями товара
    """
    item = get_object_or_404(Item, slug=item_slug)  # Получение объекта товара по его slug, или 404 если не найден
    context = {
        'item': item,  # Передача объекта товара в контекст
    }
    return render(request, 'store/item_details.html', context)  # Отображение страницы деталей товара


def tag_details(request, slug):
    """
    Представление для страницы с деталями категории (тега)
    """
    tag = get_object_or_404(ItemTag, slug=slug)  # Получение объекта категории (тега) по его slug, или 404 если не найден
    items = Item.objects.filter(tags__in=[tag])  # Получение товаров, относящихся к данной категории
    context = {
        'tag': tag,  # Передача объекта категории в контекст
        'page_obj': paginator(request, items, 3),  # Пагинация списка товаров по 3 на странице
    }
    return render(request, 'store/tag_details.html', context)  # Отображение страницы деталей категории


def tag_list(request):
    """
    Представление для страницы со списком всех категорий (тегов)
    """
    tags = ItemTag.objects.all()  # Получение всех категорий (тегов)
    context = {
        'page_obj': paginator(request, tags, 6),  # Пагинация списка категорий по 6 на странице
    }
    return render(request, 'store/tag_list.html', context)  # Отображение страницы со списком категорий


# Viewset для работы с категориями товара
class ItemTagViewSet(viewsets.ModelViewSet):
    queryset = ItemTag.objects.all()
    serializer_class = ItemTagSerializer    # Указываем сериализатор для модели ItemTag


# Viewset для работы с товарами
class ItemViewSet(viewsets.ModelViewSet):
    queryset = Item.objects.all()
    serializer_class = ItemSerializer       # Указываем сериализатор для модели Item
    filter_backends = [DjangoFilterBackend]
    filterset_class = ItemFilter


    @action(methods=['GET'], detail=False) # detail=False работает с коллекцией объектов (на список), доступ без указания PK в URL
    def list_discounted_items(self, request):
        """
        Запрос для фильтрации товаров со скидкой
        """
        # Фильтруем товары, где цена меньше старой цены
        discounted_items = Item.objects.filter(price__lt=F('old_price'))
        '''
        F - объект, который используется для ссылки на поля модели внутри запросов
        Без F вам нужно было бы сначала получить значение одного поля, а затем сравнить его с другим полем.
        F позволяет делать это в самом запросе, на уровне базы данных.
        '''
        serializer = self.get_serializer(discounted_items, many=True)
        return Response(serializer.data)


    @action(methods=['POST'], detail=True) #detail=True работает с одним объектом, доступ через PK
    def update_item_price(self, request, pk=None):
        """
        Запрос для обновления цены товара
        """
        # Обновляем цену для конкретного товара
        item = self.get_object()
        price = request.data.get('price')

        # Валидация на правильность значения цены
        if price is None:
            return Response({'error': 'Цена не предоставлена'}, status=status.HTTP_400_BAD_REQUEST)

        try:
            price = float(price)
            if price < 0:
                return Response({'error': 'Цена должна быть больше нуля'}, status=status.HTTP_400_BAD_REQUEST)
        except ValueError:
            return Response({'error': 'Неверное значение цены'}, status=status.HTTP_400_BAD_REQUEST)

        item.price = price
        item.save()
        return Response({'status': 'Цена обновлена', 'price': price}, status=status.HTTP_200_OK)

class ItemQFilterView(APIView):
    def get(self, request, *args, **kwargs):
        """
        ?? Представление для фильтрации ??
        """
        items = Item.objects.filter(
            (Q(price__lt=5000) | Q(is_available=True)) & ~Q(old_price__isnull=True)
        )
        serializer = ItemSerializer(items, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    '''
        Q — это объект из модуля django.db.models, который используется для создания сложных запросов в Django ORM.
        Он позволяет строить запросы с помощью логических операторов AND, OR и NOT (&, |, ~)
    '''

    # Запрос 1 с Q: товары, где:
    @action(methods=['GET'], detail=False)
    def filter_by_name_and_price(self, request):
        """
        Фильтрация товаров по названию и цене. А также исключение товаров
        """
        filtered_items = Item.objects.filter(
            (Q(title__startswith='Джинсы')) &  # Название начинается на 'Джинсы'
            (Q(price__lt=1500) | Q(price__gt=2500)) &  # Цена < 1500 или > 2500
            ~Q(price=F('old_price'))  # ~ Исключаем товары, у которых новая цена равна старой
        )
        serializer = self.get_serializer(filtered_items, many=True)
        return Response(serializer.data)

    # Запрос 2 с Q: товары, где:
    @action(methods=['GET'], detail=False)
    def filter_by_date_and_price_difference(self, request):
        """
        Фильтрация товаров по дате создания и разницей в цене. А также исключение товаров
        """
        filtered_items = Item.objects.filter(
            Q(pub_date__gte='2024-01-01') &  # Созданы после 2024-01-01
            Q(old_price__gt=F('price') + 400) &  # Разница между старой и новой ценой больше 400
            ~(
                    Q(title__startswith='Джинсы') |  # Исключаем товары, где название начинается на 'Джинсы'
                    Q(title__icontains='товар')  # Или название содержит 'товар'
            )
        )
        serializer = self.get_serializer(filtered_items, many=True)
        return Response(serializer.data)


# class ItemSerializer(serializers.ModelSerializer):
#     class Meta:
#         model = Item
#         fields = ['id', 'title', 'description', 'price', 'old_price', 'is_available', 'slug', 'pub_date', 'image']
#


# Представление для отображения истории изменений товара.
def item_history(request, item_slug):
    """
    Представление для отображения истории изменений товара
    """
    item = get_object_or_404(Item, slug=item_slug)
    history = ChangeHistory.objects.filter(object_type='Item', object_id=item.id).order_by('-timestamp')
    context = {
        'item': item,
        'history': history,
    }
    return render(request, 'store/item_history.html', context)

OnlineStore/templates/store/item_details.html
{% extends "base.html" %}
<!-- Наследование от базового шаблона base.html -->

{% block content %}
<!-- Начало блока content, который будет вставлен в блок content базового шаблона -->

{% load static %}
<!-- Загрузка тега static для работы сo статическими файлами -->

<h2>{{ item.title }}</h2>
<!-- Вывод заголовка товара -->

<p>Товар принадлежит к категории
<!-- Параграф с информацией о категории товара -->

{% for tag in item.tags.all %}
    <!-- Цикл для вывода всех тегов товара -->
    <b><a href="{% url 'store:tag_details' tag.slug %}">{{ tag }}</a></b>
    <!-- Ссылка на страницу с деталями тега -->
    {% if not forloop.last %},{% endif %}
    <!-- Если это не последний тег, выводим запятую -->
{% endfor %}
</p>

{% if item.image %}
    <!-- Проверка наличия изображения товара -->
    <p><span class="image left"><img src="{{ item.image.url }}" alt="" style="max-width: 200px; max-height: 200px;"/>
    <!-- Вывод изображения товара с ограничением размеров -->
{% else %}
    <!-- Если изображение отсутствует, выводим запасное изображение -->
    <p><span class="image left"><img src="{% static "images/pic14.jpg" %}" alt="" />
{% endif %}
    <a href="{% url 'cart:add_to_cart' item.slug %}" class="button small" style="margin-top:10px;">
        Добавить в корзину</a>
    <!-- Кнопка для добавления товара в корзину -->
    </span>
    {{ item.description }}{{ item.description }}
    <!-- Описание товара -->
</p>

{% if item.old_price %}
    <!-- Проверка наличия старой цены -->
    <p>Старая цена: <s>{{ item.old_price }} рублей</s>
    <!-- Вывод старой цены со скидкой -->
    Новая цена: <b>{{ item.price }}</b> рублей </p>
    <!-- Вывод новой цены без скидки -->
{% else %}
    <!-- Если нет старой цены, выводим только текущую цену -->
    <p>Цена: <b>{{ item.price }}</b> рублей </p>
{% endif %}
<!-- Конец условного блока для проверки наличия старой цены -->

{% endblock %}
<!-- Конец блока content -->

OnlineStore/templates/store/item_history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>История изменений товара</title>
</head>
<body>
    <h1>История изменений товара: {{ item.title }}</h1>
<table>
    <thead>
        <tr>
            <th>Дата</th>
            <th>Тип изменения</th>
            <th>Старые значения</th>
            <th>Новые значения</th>
        </tr>
    </thead>
    <tbody>
        {% for change in history %}
            <tr>
                <td>{{ change.timestamp }}</td>
                <td>{{ change.get_change_type_display }}</td>
                <td>{{ change.old_value }}</td>
                <td>{{ change.new_value }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

</body>
</html>

OnlineStore/templates/store/main_page.html
{% extends "base.html" %}
<!-- Наследование от базового шаблона base.html -->

{% block content %}
<!-- Начало блока content, который будет вставлен в блок content базового шаблона -->

{% load static %}
<!-- Загрузка тега static для работы с статическими файлами -->

<h1>Hype Shop: Онлайн-магазин хайповой одежды<br /></h1>
<!-- Заголовок главной страницы -->

<p>Мой проект - это современный интернет-магазин, который был разработан с использованием передовых технологий веб-разработки. Использовался язык программирования Python и его фреймворк Django для создания серверной части сайта.</p>
<!-- Описание проекта и используемых технологий -->

<p>Для создания пользовательского интерфейса были использованы языки HTML, CSS и JavaScript. Большее количество шаблонов было взято с <a href="http://html5up.net">HTML5 UP</a></p>
<!-- Информация о использованных технологиях и источниках шаблонов -->

<p>Я также использовал SQLite для хранения данных, таких как информация о товарах и заказах.</p>
<!-- Упоминание использования базы данных SQLite -->

<section class="tiles">
<!-- Начало секции с товарами -->

    {% for item in page_obj %}
    <!-- Цикл для вывода каждого товара -->

    <article class="style{{ range|random }}">
    <!-- Один товар с классом style и случайным номером в диапазоне range -->

        <span class="image">
        <!-- Блок с изображением товара -->

        {% if item.image %}
            <!-- Проверка наличия изображения товара -->
            <img src="{{ item.image.url }}" alt="" style="width: 353px; height: 326px;" />
            <!-- Вывод изображения с заданными размерами -->
        {% else %}
            <!-- Если изображение отсутствует, выводим запасное изображение -->
            <img src="{% static "images/pic01.jpg" %}" alt="" />
        {% endif %}

        </span>

        <a href="{% url 'store:item_details' item.slug %}">
        <!-- Ссылка на страницу с деталями товара -->

            <div class="tag">
            <!-- Блок с тегами товара -->

                <object>
                <!-- Объект для вложенных ссылок на теги -->

                    {% for tag in item.tags.all %}
                        <!-- Цикл для вывода всех тегов товара -->
                        <a href="{% url 'store:tag_details' tag.slug %}" style="color: white">{{ tag }}</a>
                        <!-- Ссылка на страницу с деталями тега -->
                        {% if not forloop.last %},{% endif %}
                        <!-- Если это не последний тег, выводим запятую -->
                    {% endfor %}

                </object><br />
                <!-- Завершение блока тегов и перевод строки -->

            </div>

            <h2>{{ item.title }}</h2>
            <!-- Заголовок товара -->

            <div class="content">
            <!-- Блок с описанием товара -->

                <p>{{ item.description|truncatechars:150 }}</p>
                <!-- Вывод описания товара с обрезкой до 150 символов -->

            </div>

        </a>

    </article>
    <!-- Завершение блока с одним товаром -->

    {% endfor %}
    <!-- Завершение цикла для вывода товаров -->

</section>
<!-- Завершение секции с товарами -->

<!-- Добавляем скрипт для загрузки товаров через API -->
<script>
  document.addEventListener('DOMContentLoaded', function () {
    fetch('/api/items/')
      .then(response => response.json())
      .then(data => {
        const productList = document.getElementById('product-list');
        data.forEach(item => {
          const productHTML = `
            <article class="style${Math.floor(Math.random() * 6) + 1}">
              <span class="image">
                <img src="${item.image ? item.image : '{% static "images/pic01.jpg" %}'}" alt="" style="width: 353px; height: 326px;" />
              </span>
              <a href="/${item.slug}">
                <div class="tag">
                  ${item.tags.map(tag => `<a href="/category-details/${tag.slug}" style="color: white">${tag.name}</a>`).join(', ')}
                </div>
                <h2>${item.title}</h2>
                <div class="content">
                  <p>${item.description.substring(0, 150)}...</p>
                </div>
              </a>
            </article>
          `;
          productList.innerHTML += productHTML;
        });
      })
      .catch(error => console.error('Error:', error));
  });
</script>


{% endblock %}
<!-- Завершение блока content -->

OnlineStore/templates/store/tag_details.html
{% extends "base.html" %}
<!-- Наследование от базового шаблона base.html -->

{% block content %}
<!-- Начало блока content, который будет вставлен в блок content базового шаблона -->

{% load static %}
<!-- Загрузка тега static для работы с статическими файлами -->

    <h2>{{ tag.name }}</h2>
    <!-- Заголовок страницы с названием тега -->

    Количество товаров:&ensp;{{ tag.items.count }}
    <!-- Вывод количества товаров, относящихся к данному тегу -->

    <p><a href="{% url 'store:tag_list'%}"><b>Все категории</b></a></p>
    <!-- Ссылка на страницу со всеми категориями товаров -->

    <hr>
    <!-- Горизонтальная линия для разделения -->

{% for item in page_obj %}
<!-- Цикл для вывода каждого товара из списка по данному тегу -->

    <a href="{% url 'store:item_details' item.slug %}"><b>{{ item.title }}</b></a>
    <!-- Ссылка на страницу с деталями товара и его заголовок -->

    <p><span class="image left">
        <!-- Блок с изображением товара -->

        {% if item.image %}
            <!-- Проверка наличия изображения товара -->
            <img src="{{ item.image.url }}" alt="" style="max-width: 200px; max-height: 200px;"/>
            <!-- Вывод изображения с заданными максимальными размерами -->
        {% else %}
            <!-- Если изображение отсутствует, выводим запасное изображение -->
            <img src="{% static "images/pic01.jpg" %}" alt="" />
        {% endif %}

        <a href="{% url 'cart:add_to_cart' item.slug %}" class="button small" style="margin-top:10px;">
            Добавить в корзину</a>
        <!-- Ссылка для добавления товара в корзину -->

        </span>
    </p>
    <p>{{ item.description }}</p>
    <!-- Вывод описания товара -->

    {% if item.old_price %}
        <!-- Проверка наличия старой цены товара -->
        <p>Старая цена: <s>{{ item.old_price }} рублей</s>
        Новая цена: <b>{{ item.price }}</b> рублей </p>
        <!-- Вывод старой и новой цен товара -->
    {% else %}
        <!-- Если старой цены нет, выводим только новую цену -->
        <p>Цена: <b>{{ item.price }}</b> рублей </p>
    {% endif %}

    {% if not forloop.last %}<hr>{% endif %}
    <!-- Если это не последний товар в списке, выводим горизонтальную линию -->

{% endfor %}
<!-- Завершение цикла для вывода товаров -->

{% endblock %}
<!-- Завершение блока content -->

OnlineStore/templates/store/tag_list.html
{% extends "base.html" %}
<!-- Наследование от базового шаблона base.html -->

{% block content %}
<!-- Начало блока content, который будет вставлен в блок content базового шаблона -->

{% load static %}
<!-- Загрузка тега static для работы с статическими файлами -->

    <h2>Список всех категорий</h2>
    <!-- Заголовок страницы -->

    <hr>
    <!-- Горизонтальная линия для разделения -->

{% for tag in page_obj %}
<!-- Цикл для вывода каждой категории -->

    <a href="{% url 'store:tag_details' tag.slug %}"><b>{{ tag.name }}</b></a>
    <!-- Ссылка на страницу с деталями категории и ее название -->

    <p><span class="image ">
        <!-- Блок с изображением категории, выравненным справа -->

        {% if tag.image %}
            <!-- Проверка наличия изображения категории -->
            <img src="{{ tag.image.url }}" alt="" style="width: 200px; height: 200px;"/>
            <!-- Вывод изображения с заданными размерами -->
        {% else %}
            <!-- Если изображение отсутствует, выводим запасное изображение -->
            <img src="{% static "images/pic14.jpg" %}" alt="" />
        {% endif %}

    </span>{{tag.description}}{{tag.description}}</p>
    <!-- Вывод описания категории -->

    {% if not forloop.last %}<hr>{% endif %}
    <!-- Если это не последняя категория в списке, выводим горизонтальную линию -->

{% endfor %}
<!-- Завершение цикла для вывода категорий -->

{% endblock %}
<!-- Завершение блока content -->