OnlineStore/OnlineStore/urls.py
from django.conf import settings  # Импортируем настройки Django
from django.conf.urls.static import (
    static, )  # Импортируем функцию static для обслуживания статических файлов
from django.contrib import admin  # Импортируем модуль администрирования Django
from django.urls import (
    include,
    path,
)  # Импортируем функции include и path для маршрутизации URL

urlpatterns = [
    path("admin/", admin.site.urls),  # URL для панели администратора Django
    path("cart/", include("cart.urls")),  # URL для приложения корзины
    path("about/", include("about.urls")),  # URL для страницы "О нас"
    path("checkout/", include("checkout.urls")),  # URL для оформления заказа
    path("users/", include("users.urls")),  # URL для пользовательских профилей
    path("", include("store.urls")),  # Основной URL для магазина
    path("", include("django.contrib.auth.urls")
         ),  # URL для авторизации и управления пользователями
    path("api/", include("store.api_urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT
                          )  # Добавляем URL для медиафайлов в режиме отладки
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )  # Добавляем URL для статических файлов в режиме отладки

OnlineStore/cart/urls.py
# Импортируем функцию path для создания URL-адресов
from django.urls import path
# Импортируем представления из текущего приложения
from .views import add_to_cart, cart, delete_cart_item, update_cart_item, update_cart_item_form

# Устанавливаем пространство имен для приложения
app_name = 'cart'

# Определяем список URL-адресов
urlpatterns = [
    path('', cart, name='cart'),                                                             # URL для отображения корзины
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),                          # URL для добавления товара в корзину
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),             # URL для удаления товара из корзины
    path('update_cart_item/', update_cart_item, name='update_cart_item'),                    # URL для обновления количества товара в корзине через AJAX
    path('update/<int:cart_item_id>/', update_cart_item_form, name='update_cart_item_form'), # URL для формы обновления количества товара
]

OnlineStore/users/urls.py
# Импортируем необходимые представления из django.contrib.auth.views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)

# Импортируем path и reverse_lazy из django.urls для работы с URL и
# отложенными URL-обратками
from django.urls import path, reverse_lazy

# Импортируем пользовательские представления из текущего приложения
from .views import SignUp, feedback_processing, profile, user_orders

# Указываем пространство имен для приложения, чтобы отличать URL разных
# приложений
app_name = "users"

# Определяем список URL-шаблонов для текущего приложения
urlpatterns = [
    # URL для просмотра заказов пользователя, связанный с представлением
    # user_orders
    path("orders/", user_orders, name="user_orders"),
    # URL для просмотра профиля пользователя, связанный с представлением
    # profile
    path("profile/", profile, name="profile"),
    # URL для обработки обратной связи, связанный с представлением
    # feedback_processing
    path("feedback-processing/",
         feedback_processing,
         name="feedback_processing"),
    # URL для выхода из системы, использующий стандартное представление
    # LogoutView
    path(
        "auth/logout/",
        LogoutView.as_view(template_name="users/logged_out.html"
                           ),  # Указываем шаблон для отображения после выхода
        name="logout",
    ),
    # URL для регистрации нового пользователя, связанный с представлением
    # SignUp
    path("auth/signup/", SignUp.as_view(), name="signup"),
    # URL для входа в систему, использующий стандартное представление LoginView
    path(
        "auth/login/",
        LoginView.as_view(template_name="users/login.html"
                          ),  # Указываем шаблон для отображения формы входа
        name="login",
    ),
    # URL для сброса пароля, использующий стандартное представление
    # PasswordResetView
    path(
        "auth/password_reset/",
        PasswordResetView.as_view(
            # Шаблон для формы сброса пароля
            template_name="users/managment/password_reset_form.html",
            # Шаблон для email сброса пароля
            email_template_name="users/managment/password_reset_email.html",
            success_url=reverse_lazy(
                "users:password_reset_done"
            ),  # URL для перенаправления после успешного сброса
        ),
        name="password_reset_form",
    ),
    # URL для подтверждения сброса пароля, использующий стандартное
    # представление PasswordResetDoneView
    path(
        "auth/password_reset/done/",
        PasswordResetDoneView.as_view(
            # Шаблон для отображения после отправки email
            template_name="users/managment/password_reset_done.html"),
        name="password_reset_done",
    ),
    # URL для завершения сброса пароля, использующий стандартное представление
    # PasswordResetCompleteView
    path(
        "auth/reset/done/",
        PasswordResetCompleteView.as_view(
            # Шаблон для отображения после успешного сброса
            template_name="users/managment/reset_done.html"),
        name="reset_done",
    ),
    # URL для подтверждения сброса пароля, использующий стандартное
    # представление PasswordResetConfirmView
    path(
        "auth/password_reset_confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            # Шаблон для формы подтверждения сброса
            template_name="users/managment/password_reset_confirm.html",
            success_url=reverse_lazy(
                "users:password_reset_complete"
            ),  # URL для перенаправления после подтверждения
        ),
        name="password_reset_confirm",
    ),
    # URL для изменения пароля, использующий стандартное представление
    # PasswordChangeView
    path(
        "auth/password_change/",
        PasswordChangeView.as_view(
            # Шаблон для формы изменения пароля
            template_name="users/managment/password_change_form.html",
            success_url=reverse_lazy(
                "users:password_change_done"
            ),  # URL для перенаправления после изменения
        ),
        name="password_change",
    ),
    # URL для подтверждения изменения пароля, использующий стандартное
    # представление PasswordChangeDoneView
    path(
        "auth/password_change/done/",
        PasswordChangeDoneView.as_view(
            # Шаблон для отображения после изменения
            template_name="users/managment/password_change_done.html"),
        name="password_change_done",
    ),
]

OnlineStore/checkout/models.py
from django.contrib.auth.models import User
from django.db import models

from store.models import Item


class Order(models.Model):
    # Выборы способа оплаты
    PAYMENT_METHOD_CHOICES = [
        ("cash_courier", "Наличными курьеру"),
        ("card_courier", "Картой курьеру"),
        ("card_online", "Картой онлайн"),
    ]
    # Выборы статуса заказа
    STATUS_CHOICES = [
        ("created", "Создан"),
        ("processing", "Обрабатывается"),
        ("shipped", "Отправлен"),
        ("delivered", "Доставлен"),
        ("canceled", "Отменен"),
    ]
    # Поле для выбора способа оплаты
    payment_method = models.CharField(
        max_length=20,
        choices=PAYMENT_METHOD_CHOICES,
        verbose_name="Способ оплаты",
    )
    # Внешний ключ к модели пользователя Django
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="orders",
        verbose_name="Покупатель",
    )
    # Дата и время создания заказа
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания",
    )
    # Статус заказа
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="created",
        verbose_name="Статус",
    )

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ["-created_at"]

    @property
    def total_price(self):
        # Вычисление общей стоимости заказа
        total_price = sum(order_item.total_price
                          for order_item in self.items.all())
        return total_price

    def __str__(self):
        # Строковое представление объекта заказа
        return f"Заказ номер {self.id} для {self.user}"


class OrderItem(models.Model):
    # Внешний ключ к заказу
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name="items",
        verbose_name="Заказ",
    )
    # Внешний ключ к товару
    item = models.ForeignKey(
        Item,
        on_delete=models.CASCADE,
        verbose_name="Товар",
    )
    # Количество товара в заказе
    quantity = models.PositiveIntegerField(
        default=1,
        verbose_name="Количество",
    )
    # Цена товара в момент заказа
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name="Цена",
    )

    class Meta:
        verbose_name = "Товар в заказе"
        verbose_name_plural = "Товары в заказе"

    @property
    def total_price(self):
        # Вычисление общей стоимости данной позиции в заказе
        total_price = self.quantity * self.item.price
        return total_price

    def __str__(self):
        # Строковое представление объекта позиции заказа
        return f"{self.quantity} x {self.item.title} in Order {self.order.id}"


class ShippingAddress(models.Model):
    # Имя получателя
    first_name = models.CharField(
        max_length=50,
        verbose_name="Имя",
    )
    # Фамилия получателя
    last_name = models.CharField(
        max_length=50,
        verbose_name="Фамилия",
    )
    # Email получателя
    email = models.EmailField(verbose_name="Почта", )
    # Телефон получателя
    phone = models.CharField(
        max_length=20,
        verbose_name="Телефон",
    )
    # Первая строка адреса доставки
    address_line_1 = models.CharField(
        max_length=200,
        verbose_name="Адрес",
    )
    # Вторая строка адреса доставки (дополнительно)
    address_line_2 = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        verbose_name="Адрес (дополнительно)",
    )
    # Связь с заказом через OneToOneField
    order = models.OneToOneField(
        Order,
        on_delete=models.CASCADE,
        related_name="shipping_address",
        verbose_name="Заказ",
    )

    class Meta:
        verbose_name = "Адрес доставки"
        verbose_name_plural = "Адреса доставки"

    def __str__(self):
        # Строковое представление объекта адреса доставки
        return f"""
        {self.address_line_1} {self.address_line_2}
        Для: {self.first_name} {self.last_name},
        Почта: {self.email},
        Телефон: {self.phone}
        """

OnlineStore/users/models.py
from django.db import models  # Импортируем модуль моделей Django


class Feedback(models.Model):
    """Модель обратной связи покупателя."""

    feedback_name = models.CharField(
        max_length=50,
        verbose_name="Имя покупателя")  # Поле для имени покупателя
    feedback_email = models.EmailField(
        verbose_name="Почта покупателя"
    )  # Поле для электронной почты покупателя
    feedback_message = models.TextField(
        verbose_name="Текст")  # Поле для текста обратной связи
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания")  # Поле для даты создания записи

    class Meta:
        verbose_name = "Обратная связь покупателя"  # Отображаемое имя модели в админке
        # Множественное отображаемое имя модели в админке
        verbose_name_plural = "Обратная связь покупателя"

    def __str__(self):
        return self.feedback_message[:
                                     30]  # Возвращаем первые 30 символов текста обратной связи при преобразовании объекта в строку

OnlineStore/users/forms.py
from django import forms  # Импортируем модуль форм Django
from django.contrib.auth import (
    get_user_model, )  # Импортируем функцию для получения модели пользователя
from django.contrib.auth.forms import (
    UserCreationForm, )  # Импортируем стандартную форму создания пользователя
from .models import Feedback  # Импортируем модель Feedback из текущего приложения

User = (
    get_user_model()
)  # Получаем текущую модель пользователя, которая может быть заменена в проекте


class CreationForm(UserCreationForm):
    """Форма для создания нового пользователя."""

    class Meta(UserCreationForm.Meta):
        model = User  # Указываем модель пользователя для этой формы
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
        )  # Указываем поля, которые будут отображаться в форме


class FeedbackForm(forms.ModelForm):
    """Форма для обратной связи покупателя."""

    class Meta:
        model = Feedback  # Указываем модель Feedback для этой формы
        fields = [
            "feedback_name",
            "feedback_email",
            "feedback_message",
        ]  # Указываем поля, которые будут отображаться в форме

OnlineStore/users/views.py
# Импортируем необходимые модули
import asyncio

import telegram
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from OnlineStore.settings import TELEGRAM_CHAT_ID, TELEGRAM_TOKEN
from checkout.models import Order
from .forms import CreationForm, FeedbackForm
from .models import Feedback


@login_required
def user_orders(request):
    """
    Представление для отображения списка заказов пользователя.
    Декоратор @login_required требует аутентификации пользователя.
    """
    orders = Order.objects.filter(
        user=request.user)  # Получаем заказы текущего пользователя
    context = {
        "orders": orders,  # Передаем заказы в контекст шаблона
    }
    return render(request, "users/user_orders.html",
                  context)  # Отображаем шаблон user_orders.html с контекстом


@login_required
def profile(request):
    """
    Представление для отображения профиля пользователя.
    Декоратор @login_required требует аутентификации пользователя.
    """
    return render(request,
                  "users/profile.html")  # Отображаем шаблон profile.html


class SignUp(CreateView):
    """
    Класс-представление для регистрации нового пользователя.
    Использует форму CreationForm.
    """

    form_class = CreationForm  # Форма для регистрации
    success_url = reverse_lazy(
        "store:home")  # URL для перенаправления после успешной регистрации
    template_name = "users/signup.html"  # Шаблон для отображения формы регистрации


async def send_telegram_message(message):
    """
    Асинхронная функция для отправки сообщения в Telegram.
    """
    bot = telegram.Bot(
        token=TELEGRAM_TOKEN)  # Создаем экземпляр бота с указанным токеном
    chat_id = TELEGRAM_CHAT_ID  # ID чата, куда будет отправлено сообщение
    # Отправляем сообщение в чат
    await bot.send_message(chat_id=chat_id, text=message)


def feedback_processing(request):
    """
    Представление для приема и обработки обратной связи от пользователей.
    """
    if request.method == "POST":  # Проверяем, что запрос был методом POST
        form = FeedbackForm(request.POST)  # Заполняем форму данными из запроса
        if form.is_valid():  # Проверяем, что форма валидна
            feedback = Feedback(
                feedback_name=form.cleaned_data["feedback_name"],
                feedback_email=form.cleaned_data["feedback_email"],
                feedback_message=form.cleaned_data["feedback_message"],
            )
            feedback.save()  # Сохраняем данные обратной связи в базе данных

            # Отправляем сообщение в Telegram
            message = f"Новое сообщение от {feedback.feedback_name} ({feedback.feedback_email}): {feedback.feedback_message}"
            asyncio.run(send_telegram_message(
                message))  # Асинхронно отправляем сообщение

            return render(request, "users/feedback_success.html"
                          )  # Отображаем шаблон успешной отправки
    return render(
        request, "users/feedback_failed.html"
    )  # Отображаем шаблон неудачной отправки, если что-то пошло не так

OnlineStore/templates/users/feedback_failed.html
{% extends 'base.html' %}
<!-- Наследование от базового шаблона base.html -->

{% block content %}
<!-- Начало блока content, который будет вставлен в блок content базового шаблона -->

  <h1>Извините, Ваш отзыв был не обработан =(</h1>
  <!-- Заголовок страницы с извинением за необработанный отзыв -->

  <p>К сожалению, Ваше сообщение не было обработано. Возможно, форма не была корректно заполнена.</p>
  <!-- Текстовое сообщение о возможной причине необработки отзыва -->

  <p>Если же Вы уверены что форма заполнена корректно, свяжитесь с нами по почте или по социальным сетям. Ссылки на них расположены внизу страницы.</p>
  <!-- Подсказка пользователю о возможности связаться по другим каналам для уточнения информации -->

{% endblock %}
<!-- Завершение блока content -->

OnlineStore/templates/users/feedback_success.html
{% extends 'base.html' %}
<!-- Наследование от базового шаблона base.html -->

{% block content %}
<!-- Начало блока content, который будет вставлен в блок content базового шаблона -->

  <h1>Спасибо за отзыв!</h1>
  <!-- Заголовок страницы с благодарностью за отправленный отзыв -->

  <p>Ваше сообщение уже принято в обработку. В ближайшее время мы свяжемся с Вами.</p>
  <!-- Текстовое сообщение о том, что отзыв успешно отправлен и будет обработан в ближайшее время -->

{% endblock %}
<!-- Завершение блока content -->

OnlineStore/templates/users/logged_out.html
{% extends 'base.html' %}
<!-- Наследование от базового шаблона base.html -->

{% block content %}
<!-- Начало блока content, который будет вставлен в блок content базового шаблона -->

  <h1>Вы успешно вышли из системы</h1>
  <!-- Заголовок страницы, уведомляющий пользователя о успешном выходе из системы -->

  <p>Вернуться на <a href="{% url 'users:login' %}">страницу входа</a>.</p>
  <!-- Сообщение с ссылкой на страницу входа, куда пользователь может вернуться -->

{% endblock %}
<!-- Завершение блока content -->

OnlineStore/templates/users/login.html
{% extends "base.html" %}
<!-- Наследование от базового шаблона base.html -->

{% load static %}
<!-- Загрузка статических файлов -->

{% block css %}
<link rel="stylesheet" href="{% static "assets/css/users.css"%}" />
<!-- Подключение таблицы стилей users.css из статических файлов -->
{% endblock %}

{% block content %}
<!-- Начало блока content, который будет вставлен в блок content базового шаблона -->

<h1>Войти на сайт</h1>
<!-- Заголовок формы входа -->

<form method="post">
<!-- Форма для входа пользователя, метод POST -->

  {% csrf_token %}
  <!-- CSRF-токен для безопасности формы -->

  {% for field in form %}
  <!-- Цикл для отображения полей формы -->

  <p>
    <div class="form-field">
      <label for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }}
      <!-- Отображение поля формы с его меткой -->
    </div>

    {% if form.errors %}
    <!-- Проверка наличия ошибок в форме -->
    <div class="alert alert-danger">
      {% for field, errors in form.errors.items %}
        {% for error in errors %}
          <span class="error-message">{{ error }}</span>
          <!-- Отображение ошибок, если они есть -->
        {% endfor %}
      {% endfor %}
    </div>
    {% endif %}
  </p>
  {% endfor %}
  <!-- Завершение цикла для полей формы -->

  <br>
  <button type="submit">Войти</button>
  <!-- Кнопка для отправки формы -->

</form>

<div>
  Еще не зарегистрированы?
  <a href="{% url 'users:signup' %}">Зарегистрироваться</a>
  <!-- Ссылка для перехода на страницу регистрации -->
</div>

<a href="{% url 'users:password_reset_form' %}">
  Забыли пароль?
</a>
<!-- Ссылка для перехода на страницу сброса пароля -->

{% endblock %}
<!-- Завершение блока content -->

OnlineStore/templates/users/profile.html
{% extends 'base.html' %}
<!-- Наследование от базового шаблона base.html -->

{% block content %}
<!-- Начало блока content, который будет вставлен в блок content базового шаблона -->

<h1>Ваш профиль</h1>
<!-- Заголовок раздела с профилем пользователя -->

<p>Здравствуйте, {{ request.user.get_username }}. Всего у вас <strong>{{ request.user.orders.count }}</strong> заказов.</p>
<!-- Приветственное сообщение с именем пользователя и количеством его заказов -->

<p>Ваши заказы: <a href="{% url 'users:user_orders' %}">Перейти к заказам</a></p>
<!-- Ссылка для перехода к странице с заказами пользователя -->

<p>Если вы хотите выйти из системы: <a href="{% url 'users:logout' %}">Выйти</a></p>
<!-- Ссылка для выхода из учетной записи -->

<p>Если вы хотите сменить пароль: <a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
<!-- Ссылка для перехода к форме смены пароля -->

{% endblock %}
<!-- Завершение блока content -->

OnlineStore/templates/users/signup.html
{% extends "base.html" %}
<!-- Наследование от базового шаблона base.html -->

{% load static %}
<!-- Загрузка статических файлов -->

{% block css %}
<!-- Начало блока css для подключения CSS стилей -->

<link rel="stylesheet" href="{% static "assets/css/users.css"%}" />
<!-- Подключение CSS файла для стилизации формы -->

{% endblock %}
<!-- Завершение блока css -->

{% block content %}
<!-- Начало блока content, который будет вставлен в блок content базового шаблона -->

<h1>Зарегистрироваться</h1>
<!-- Заголовок формы регистрации -->

<form method="post" action="{% url 'users:signup' %}">
<!-- Форма для отправки данных регистрации -->

  {% csrf_token %}
  <!-- CSRF защита -->

  {% for field in form %}
  <!-- Цикл для отображения полей формы -->

  <p>
    <div class="form-field">
      <label for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }}
      <!-- Отображение метки поля и самого поля ввода -->
    </div>

    {% if form.errors %}
    <!-- Проверка на наличие ошибок в форме -->

    <div class="alert alert-danger">
      {% for error in field.errors %}
        <p>{{ error }}</p>
        <!-- Вывод ошибок, если они есть -->
      {% endfor %}
    </div>
    {% endif %}
  </p>
  {% endfor %}

  <button type="submit" class="btn btn-primary">
    Зарегистрироваться
    <!-- Кнопка для отправки формы -->
  </button>
</form>
{% endblock %}
<!-- Завершение блока content -->

OnlineStore/templates/users/user_orders.html
{% extends "base.html" %}
<!-- Наследование от базового шаблона base.html -->

{% load static %}
<!-- Загрузка статических файлов -->

{% block css %}
<!-- Начало блока css для подключения CSS стилей -->

<link rel="stylesheet" href="{% static "assets/css/profile.css"%}" />
<!-- Подключение CSS файла для стилизации профиля пользователя -->

{% endblock %}
<!-- Завершение блока css -->

{% block content %}
<!-- Начало блока content, который будет вставлен в блок content базового шаблона -->

<h1>Ваши заказы</h1>
<!-- Заголовок раздела с заказами пользователя -->

{% if orders %}
<!-- Проверка на наличие заказов у пользователя -->

  {% for order in orders %}
  <!-- Цикл для перебора всех заказов пользователя -->

  <div class="order-wrapper">
    <!-- Обертка для каждого заказа -->

    <div class="order-header">
      <!-- Заголовок заказа с адресом доставки и статусом -->

      <p>Адрес: {{ order.shipping_address }}</p>
      <!-- Отображение адреса доставки -->

      <p><strong>Статус заказа: {{ order.get_status_display }}</strong></p>
      <!-- Отображение статуса заказа с использованием метода get_status_display для получения человеко-читаемого представления статуса -->

    </div>

    <div class="table-wrapper">
      <!-- Обертка для таблицы с товарами в заказе -->

      <table class="alt">
        <!-- Таблица со стилем alt для красивого отображения -->

        <thead>
          <tr>
            <th>Название</th>
            <th>Количество</th>
            <th>Цена</th>
          </tr>
        </thead>

        <tbody>
          <!-- Тело таблицы, где отображаются товары в заказе -->

          {% for order_item in order.items.all %}
          <!-- Цикл для перебора всех товаров в текущем заказе -->

          <tr>
            <!-- Строка таблицы для каждого товара -->

            <td>{{ order_item.item.title }}</td>
            <!-- Отображение названия товара -->

            <td>{{ order_item.quantity }}</td>
            <!-- Отображение количества товара -->

            <td>{{ order_item.total_price }}</td>
            <!-- Отображение общей цены за данный товар -->

          </tr>
          {% endfor %}
          <!-- Завершение цикла для перебора товаров в заказе -->

        </tbody>

        <tfoot>
          <!-- Нижний колонтитул таблицы -->

          <tr>
            <td colspan="2"></td>
            <!-- Пустая ячейка -->

            <td><b>{{ order.total_price }}</b></td>
            <!-- Общая сумма заказа -->

          </tr>

        </tfoot>

      </table>
      <!-- Завершение таблицы -->

    </div>
    <!-- Завершение обертки для таблицы -->

  </div>
  <!-- Завершение обертки для каждого заказа -->

    {% if not forloop.last %}<hr>{% endif %}
    <!-- Добавление горизонтальной линии между заказами, если текущий заказ не последний -->

  {% endfor %}
  <!-- Завершение цикла для перебора всех заказов -->

{% else %}
<!-- Если у пользователя нет заказов -->

  <p>У вас пока нет заказов.</p>
  <!-- Сообщение о том, что у пользователя нет заказов -->

{% endif %}
<!-- Завершение условия наличия заказов -->

{% endblock %}
<!-- Завершение блока content -->